kind: pipeline
type: docker
name: default

steps:
- name: test
  image: pypy:3.7-slim
  commands:
  - pip install -r requirements.txt
  - pypy -m unittest discover tests

- name: verify
  image: pypy:3.7-slim
  commands:
  - pip install bumpversion
  - $(bumpversion --list none setup.py crash_vm/__init__.py | sed -e 's/^/export /')
  - test "v$current_version" == "$DRONE_TAG"
  when:
    ref: refs/tags/v*.*.*

- name: publish
  image: plugins/pypi
  settings:
    username: __token__
    password:
      from_secret: PYPI_ACCESS_TOKEN
    repository: https://test.pypi.org/legacy/
  when:
    ref: refs/tags/v*.*.*

trigger:
  ref:
  - refs/heads/master
  - refs/tags/v*.*.*
