#!/bin/bash

if which python3.8 ; then
    echo "Using python3.8"
    virtualenv -p python3.8 .venv
else
    echo "Using python3"
    virtualenv -p python3 .venv
fi
.venv/bin/pip install -r requirements.txt
